// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjeOwmtS-zqXj9GmaEDiUoAN5_g32lrBg',
    appId: '1:208315203575:android:e762668322b1af6814b8f2',
    messagingSenderId: '208315203575',
    projectId: 'notificationapp-496d8',
    storageBucket: 'notificationapp-496d8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlogjK6FTfJTQuUNReUAzsmOKfm5K7p1U',
    appId: '1:208315203575:ios:8d182228ca59c2d514b8f2',
    messagingSenderId: '208315203575',
    projectId: 'notificationapp-496d8',
    storageBucket: 'notificationapp-496d8.firebasestorage.app',
    androidClientId: '208315203575-7b0mbncql3s744p9bafitforfhcn3e69.apps.googleusercontent.com',
    iosClientId: '208315203575-mpdlfid3m1jeepstqdbbcv5rrvthbgu9.apps.googleusercontent.com',
    iosBundleId: 'com.snt.notificat',
  );
}
